import {
  applyVenueBalanceReservations,
  calculateVenueExposureUsd,
  countSlotExecutionBlockers,
} from "@/lib/risk";
import type { OrderIntent, PositionSnapshot, VenueBalance } from "@/lib/types";

describe("venue exposure", () => {
  it("combines current positions and open intent exposure by venue", () => {
    const positions: PositionSnapshot[] = [
      {
        id: "poly-position",
        asset: "btc",
        venue: "polymarket",
        marketRef: "poly-market",
        outcome: "UP",
        size: 10,
        averagePrice: 0.4,
        currentPrice: 0.45,
        currentValueUsd: 4.5,
        realizedPnlUsd: 0,
        unrealizedPnlUsd: 0.5,
        redeemable: false,
        mergeable: false,
        updatedAt: 1,
        raw: {},
      },
      {
        id: "kalshi-position",
        asset: "btc",
        venue: "kalshi",
        marketRef: "kalshi-market",
        outcome: "YES",
        size: 5,
        averagePrice: 0.5,
        currentPrice: 0.55,
        currentValueUsd: 2.75,
        realizedPnlUsd: 0,
        unrealizedPnlUsd: 0.25,
        redeemable: false,
        mergeable: false,
        updatedAt: 1,
        raw: {},
      },
    ];

    const openIntents: OrderIntent[] = [
      {
        id: "intent-1",
        asset: "btc",
        shadow: false,
        slotKey: "btc:slot-1",
        slotStartTs: 1,
        slotEndTs: 2,
        combination: "POLY_UP_KALSHI_NO",
        status: "hedged",
        createdAt: 1,
        updatedAt: 1,
        resolvedAt: null,
        primaryVenue: "polymarket",
        hedgeVenue: "kalshi",
        grossCost: 0.9,
        targetNotionalUsd: 50,
        maxSlippageBps: 30,
        failureReason: null,
        projectedNetProfitUsd: 2,
        realizedPnlUsd: null,
        roi: null,
        polyResolution: null,
        kalshiResolution: null,
        legs: [
          {
            id: "leg-1",
            intentId: "intent-1",
            venue: "polymarket",
            outcome: "UP",
            marketRef: "poly-market",
            tokenId: "token-1",
            side: "BUY",
            requestedPrice: 0.4,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: 0.41,
            filledSize: 50,
            feeUsd: 0.1,
            status: "hedged",
            venueOrderId: "poly-order-1",
            payoutUsd: null,
            resolvedOutcome: null,
          },
          {
            id: "leg-2",
            intentId: "intent-1",
            venue: "kalshi",
            outcome: "NO",
            marketRef: "kalshi-market",
            side: "BUY",
            requestedPrice: 0.5,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: 0.49,
            filledSize: 50,
            feeUsd: 0.1,
            status: "hedged",
            venueOrderId: "kalshi-order-1",
            payoutUsd: null,
            resolvedOutcome: null,
          },
        ],
      },
    ];

    const exposure = calculateVenueExposureUsd(positions, openIntents);

    expect(exposure.polymarket).toBeCloseTo(20.5 + 0.1 + 4.5, 4);
    expect(exposure.kalshi).toBeCloseTo(24.5 + 0.1 + 2.75, 4);
  });

  it("keeps worst-fill fees and recovery reserves across ticks", () => {
    const intent = {
      id: "intent-reserved",
      asset: "btc",
      shadow: false,
      slotKey: "btc:slot-reserved",
      slotStartTs: 1,
      slotEndTs: 2,
      combination: "POLY_UP_KALSHI_NO",
      status: "executing_primary",
      createdAt: 1,
      updatedAt: 1,
      resolvedAt: null,
      primaryVenue: "polymarket",
      hedgeVenue: "kalshi",
      grossCost: 0.9,
      targetNotionalUsd: 9,
      maxSlippageBps: 30,
      failureReason: null,
      projectedNetProfitUsd: 1,
      realizedPnlUsd: null,
      roi: null,
      polyResolution: null,
      kalshiResolution: null,
      legs: [
        {
          id: "poly-reserved",
          intentId: "intent-reserved",
          venue: "polymarket",
          outcome: "UP",
          marketRef: "poly-market",
          side: "BUY",
          requestedPrice: 0.5,
          requestedSize: 10,
          requestedNotionalUsd: 5,
          worstFillCostUsd: 5.4,
          recoveryReserveUsd: 0,
          filledPrice: null,
          filledSize: 0,
          feeUsd: 0.1,
          status: "submitted",
          venueOrderId: "poly-order",
          payoutUsd: null,
          resolvedOutcome: null,
        },
        {
          id: "kalshi-reserved",
          intentId: "intent-reserved",
          venue: "kalshi",
          outcome: "NO",
          marketRef: "kalshi-market",
          side: "BUY",
          requestedPrice: 0.4,
          requestedSize: 10,
          requestedNotionalUsd: 4,
          worstFillCostUsd: 4.3,
          recoveryReserveUsd: 2,
          filledPrice: null,
          filledSize: 0,
          feeUsd: 0.1,
          status: "pending",
          venueOrderId: null,
          payoutUsd: null,
          resolvedOutcome: null,
        },
      ],
    } as OrderIntent;

    expect(calculateVenueExposureUsd([], [intent])).toEqual({
      polymarket: 5.4,
      kalshi: 6.3,
    });
    expect(
      applyVenueBalanceReservations(
        [
          {
            venue: "polymarket",
            status: "ready",
            currency: "USDC",
            availableBalanceUsd: 20,
            totalBalanceUsd: 20,
            portfolioValueUsd: 0,
            allowanceUsd: null,
            capturedAt: 1,
            notes: [],
            raw: {},
          },
          {
            venue: "kalshi",
            status: "ready",
            currency: "USD",
            availableBalanceUsd: 20,
            totalBalanceUsd: 20,
            portfolioValueUsd: 0,
            allowanceUsd: null,
            capturedAt: 1,
            notes: [],
            raw: {},
          },
        ],
        [intent],
      ),
    ).toEqual([
      expect.objectContaining({ availableBalanceUsd: 14.6 }),
      expect.objectContaining({ availableBalanceUsd: 13.7 }),
    ]);
  });

  it("keeps filled cash reserved until a newer venue balance absorbs the fill", () => {
    const filledIntent = {
      status: "hedged",
      updatedAt: 200,
      legs: [
        {
          venue: "polymarket",
          requestedNotionalUsd: 5,
          worstFillCostUsd: 5.4,
          recoveryReserveUsd: 0,
          filledPrice: 0.5,
          filledSize: 10,
          filledAt: 300,
          feeUsd: 0.1,
          status: "hedged",
        },
        {
          venue: "kalshi",
          requestedNotionalUsd: 4,
          worstFillCostUsd: 4.3,
          recoveryReserveUsd: 2,
          filledPrice: 0.4,
          filledSize: 10,
          filledAt: 300,
          feeUsd: 0.1,
          status: "hedged",
        },
      ],
    } as unknown as OrderIntent;
    const balances: VenueBalance[] = [
      {
        venue: "polymarket",
        status: "ready",
        currency: "USDC",
        availableBalanceUsd: 20,
        totalBalanceUsd: 20,
        portfolioValueUsd: 0,
        allowanceUsd: null,
        capturedAt: 100,
        notes: [],
        raw: {},
      },
      {
        venue: "kalshi",
        status: "ready",
        currency: "USD",
        availableBalanceUsd: 20,
        totalBalanceUsd: 20,
        portfolioValueUsd: 0,
        allowanceUsd: null,
        capturedAt: 100,
        notes: [],
        raw: {},
      },
    ];

    expect(applyVenueBalanceReservations(balances, [filledIntent])).toEqual([
      expect.objectContaining({ availableBalanceUsd: 14.9 }),
      expect.objectContaining({ availableBalanceUsd: 15.9 }),
    ]);
    expect(
      applyVenueBalanceReservations(
        balances.map((balance) => ({ ...balance, capturedAt: 300 })),
        [filledIntent],
      ),
    ).toEqual([
      expect.objectContaining({ availableBalanceUsd: 14.9 }),
      expect.objectContaining({ availableBalanceUsd: 15.9 }),
    ]);
    expect(
      applyVenueBalanceReservations(
        balances.map((balance) => ({ ...balance, capturedAt: 301 })),
        [filledIntent],
      ),
    ).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ venue: "polymarket", availableBalanceUsd: 20 }),
        expect.objectContaining({ venue: "kalshi", availableBalanceUsd: 20 }),
      ]),
    );
  });

  it("does not count already hedged intents as slot execution blockers", () => {
    const openIntents: OrderIntent[] = [
      {
        id: "intent-hedged",
        asset: "btc",
        shadow: false,
        slotKey: "btc:slot-1",
        slotStartTs: 1,
        slotEndTs: 2,
        combination: "POLY_UP_KALSHI_NO",
        status: "hedged",
        createdAt: 1,
        updatedAt: 1,
        resolvedAt: null,
        primaryVenue: "polymarket",
        hedgeVenue: "kalshi",
        grossCost: 0.9,
        targetNotionalUsd: 50,
        maxSlippageBps: 30,
        failureReason: null,
        projectedNetProfitUsd: 2,
        realizedPnlUsd: null,
        roi: null,
        polyResolution: null,
        kalshiResolution: null,
        legs: [
          {
            id: "leg-1",
            intentId: "intent-hedged",
            venue: "polymarket",
            outcome: "UP",
            marketRef: "poly-market",
            tokenId: "token-1",
            side: "BUY",
            requestedPrice: 0.4,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: 0.41,
            filledSize: 50,
            feeUsd: 0.1,
            status: "hedged",
            venueOrderId: "poly-order-1",
            payoutUsd: null,
            resolvedOutcome: null,
          },
          {
            id: "leg-2",
            intentId: "intent-hedged",
            venue: "kalshi",
            outcome: "NO",
            marketRef: "kalshi-market",
            side: "BUY",
            requestedPrice: 0.5,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: 0.49,
            filledSize: 50,
            feeUsd: 0.1,
            status: "hedged",
            venueOrderId: "kalshi-order-1",
            payoutUsd: null,
            resolvedOutcome: null,
          },
        ],
      },
      {
        id: "intent-hedging",
        asset: "btc",
        shadow: false,
        slotKey: "btc:slot-1",
        slotStartTs: 1,
        slotEndTs: 2,
        combination: "POLY_DOWN_KALSHI_YES",
        status: "hedging",
        createdAt: 1,
        updatedAt: 1,
        resolvedAt: null,
        primaryVenue: "polymarket",
        hedgeVenue: "kalshi",
        grossCost: 0.9,
        targetNotionalUsd: 50,
        maxSlippageBps: 30,
        failureReason: null,
        projectedNetProfitUsd: 2,
        realizedPnlUsd: null,
        roi: null,
        polyResolution: null,
        kalshiResolution: null,
        legs: [
          {
            id: "leg-3",
            intentId: "intent-hedging",
            venue: "polymarket",
            outcome: "DOWN",
            marketRef: "poly-market-2",
            tokenId: "token-2",
            side: "BUY",
            requestedPrice: 0.4,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: 0.41,
            filledSize: 50,
            feeUsd: 0.1,
            status: "filled",
            venueOrderId: "poly-order-2",
            payoutUsd: null,
            resolvedOutcome: null,
          },
          {
            id: "leg-4",
            intentId: "intent-hedging",
            venue: "kalshi",
            outcome: "YES",
            marketRef: "kalshi-market-2",
            side: "BUY",
            requestedPrice: 0.5,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: null,
            filledSize: 0,
            feeUsd: 0,
            status: "pending",
            venueOrderId: null,
            payoutUsd: null,
            resolvedOutcome: null,
          },
        ],
      },
    ];

    expect(countSlotExecutionBlockers(openIntents, "btc:slot-1")).toBe(1);
  });
});

describe("venue balance reservations", () => {
  it("reserves in-flight venue cash globally across assets", () => {
    const balances: VenueBalance[] = [
      {
        venue: "polymarket",
        capturedAt: 1,
        status: "ready",
        currency: "USDC",
        availableBalanceUsd: 100,
        totalBalanceUsd: 100,
        portfolioValueUsd: 100,
        allowanceUsd: 100,
        notes: [],
        raw: {},
      },
      {
        venue: "kalshi",
        capturedAt: 1,
        status: "ready",
        currency: "USD",
        availableBalanceUsd: 80,
        totalBalanceUsd: 80,
        portfolioValueUsd: 80,
        allowanceUsd: null,
        notes: [],
        raw: {},
      },
    ];

    const openIntents: OrderIntent[] = [
      {
        id: "intent-btc",
        asset: "btc",
        shadow: false,
        slotKey: "btc:slot-1",
        slotStartTs: 1,
        slotEndTs: 2,
        combination: "POLY_UP_KALSHI_NO",
        status: "executing_primary",
        createdAt: 1,
        updatedAt: 1,
        resolvedAt: null,
        primaryVenue: "polymarket",
        hedgeVenue: "kalshi",
        grossCost: 0.9,
        targetNotionalUsd: 50,
        maxSlippageBps: 30,
        failureReason: null,
        projectedNetProfitUsd: 2,
        realizedPnlUsd: null,
        roi: null,
        polyResolution: null,
        kalshiResolution: null,
        legs: [
          {
            id: "leg-btc-poly",
            intentId: "intent-btc",
            venue: "polymarket",
            outcome: "UP",
            marketRef: "poly-btc",
            tokenId: "token-btc",
            side: "BUY",
            requestedPrice: 0.4,
            requestedSize: 50,
            requestedNotionalUsd: 20,
            filledPrice: null,
            filledSize: 0,
            feeUsd: 0,
            status: "pending",
            venueOrderId: null,
            payoutUsd: null,
            resolvedOutcome: null,
          },
          {
            id: "leg-btc-kalshi",
            intentId: "intent-btc",
            venue: "kalshi",
            outcome: "NO",
            marketRef: "kalshi-btc",
            side: "BUY",
            requestedPrice: 0.5,
            requestedSize: 50,
            requestedNotionalUsd: 25,
            filledPrice: null,
            filledSize: 0,
            feeUsd: 0,
            status: "submitted",
            venueOrderId: "kalshi-btc-order",
            payoutUsd: null,
            resolvedOutcome: null,
          },
        ],
      },
      {
        id: "intent-eth",
        asset: "eth",
        shadow: false,
        slotKey: "eth:slot-1",
        slotStartTs: 1,
        slotEndTs: 2,
        combination: "POLY_DOWN_KALSHI_YES",
        status: "executing_primary",
        createdAt: 1,
        updatedAt: 1,
        resolvedAt: null,
        primaryVenue: "polymarket",
        hedgeVenue: "kalshi",
        grossCost: 0.9,
        targetNotionalUsd: 50,
        maxSlippageBps: 30,
        failureReason: null,
        projectedNetProfitUsd: 2,
        realizedPnlUsd: null,
        roi: null,
        polyResolution: null,
        kalshiResolution: null,
        legs: [
          {
            id: "leg-eth-poly",
            intentId: "intent-eth",
            venue: "polymarket",
            outcome: "DOWN",
            marketRef: "poly-eth",
            tokenId: "token-eth",
            side: "BUY",
            requestedPrice: 0.5,
            requestedSize: 30,
            requestedNotionalUsd: 15,
            filledPrice: null,
            filledSize: 0,
            feeUsd: 0,
            status: "submitted",
            venueOrderId: "poly-eth-order",
            payoutUsd: null,
            resolvedOutcome: null,
          },
          {
            id: "leg-eth-kalshi",
            intentId: "intent-eth",
            venue: "kalshi",
            outcome: "YES",
            marketRef: "kalshi-eth",
            side: "BUY",
            requestedPrice: 0.45,
            requestedSize: 20,
            requestedNotionalUsd: 10,
            filledPrice: null,
            filledSize: 0,
            feeUsd: 0,
            status: "pending",
            venueOrderId: null,
            payoutUsd: null,
            resolvedOutcome: null,
          },
        ],
      },
    ];

    expect(applyVenueBalanceReservations(balances, openIntents)).toEqual([
      expect.objectContaining({
        venue: "polymarket",
        availableBalanceUsd: 65,
        notes: ["Reserved for in-flight intents: 35.00 USD"],
      }),
      expect.objectContaining({
        venue: "kalshi",
        availableBalanceUsd: 45,
        notes: ["Reserved for in-flight intents: 35.00 USD"],
      }),
    ]);
  });
});
